### ISSUE TITLE
Improve `print.robustGARCH()` and `summary.robustGARCH()` to follow `lm`

### ISSUE THREAD

**Issue by dan9401** [EchoRLiu/robustGarch#16]
1. return basic estimate info in print()
2. make summary() return a list, so the information can be easily accessed/used

**Comment by EchoRLiu** [comment]
- more compact print out: only parameters and std

**Comment by robustport** [comment]
Two comments: (1) It is really a pain in the you-know-what to not have the print method print the coefficient estimates (and I don't think it needs to do anything else, since the summary method will provide the rest of the info needed (PLEASE FIX THIS RIGHT AWAY).  (2) The "rg" in print.rg is pretty cryptic.

**Comment by robustport** [comment]
I just looked at the print method, and have the following comments:
(1)  The print method should be invoked when pressing enter at the end of the object name (does not currently do that).  (2) The print method should not include S.E.'s, as the interested user can get those from the summary method. (3) The printout currently takes up too much space, and it should have the following compact layout, keeping in mind that the user initially just needs to quickly check the coefficients of just one or several fitted models:
Model: QML
Data:  retGNCMA
Cofficients:        gamma    alpha      beta     
                              0          0.133     0.867
(3)  The print method should print the required number of digits upon request, e.g.,
print(robFitqmle, digits = 5) should result in displaying 5 significant digits.  Currently it does that for that standard errors, which will be dropped, but not the coefficient, which for some strange reason has 4 digits.

**Comment by robustport** [comment]
As for the summary method:   (1) The log-likelihood value has more digits than the values in the table above it, and should be changed to be consistent with the table, including when digits = is used, e.g., digits = 5.  (2) class(summary(robFitqmle))
just prints summary(robFitqmle), instead of a list, which is needed, but can be deferred until later. (3) It would be nice if the Data:  entry could included the frequencey, e.g., weekly GNCMA, and if the Observations entry could list the start and end date, as well as the number of observations.
